<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE persons [
    <!ELEMENT lastname (#PCDATA)>
    <!ELEMENT firstname (#PCDATA)>
    <!ELEMENT residence (#PCDATA)>
    <!ELEMENT children (person*)>
    <!ELEMENT person (firstname, (lastname?), (children?), (residence?))>
    <!ELEMENT persons (person+)>
    <!ATTLIST person id ID #REQUIRED>
    <!ATTLIST person friends IDREFS #IMPLIED>
	<!ATTLIST persons file CDATA #IMPLIED>
    ]>
<?mach was draus?>
<persons file="this">
    <!-- Hier beginnen die Daten -->
    <person id="p-2">
        <firstname>Pu</firstname>
        <lastname>Bison</lastname>
    </person>
    <person id="p-1">
        <firstname>Christopher</firstname>
        <lastname>Columbus</lastname>
    </person>
    <person id="p-3">
        <firstname>Euler</firstname>
        <residence>Schweiz</residence>
        <!-- zusÃ¤tzlich -->
    </person>
</persons>
